Add route before view
When the view is added before the route the following error occurs while running c2cgeoportal's unit tests:

ConfigurationError: No route named deps.js found for view registration